// demos/vue/src/components/Profile.vue
<template>
  <section>
    <h1>Profile</h1>
    <div class="card">
      <div class="form-field">
        <label for="spa-profile-field">Display name</label>
        <input id="spa-profile-field" type="text" placeholder="Your name" />
      </div>
      <button class="btn-primary" type="button">Save</button>
    </div>
  </section>
</template>

// demo/src/svelte/Profile.svelte
<section>
  <h1>Profile</h1>
  <div class="card">
    <div class="form-field">
      <label for="spa-profile-field">Display name</label>
      <input id="spa-profile-field" type="text" placeholder="Your name" />
    </div>
    <button class="btn-primary" type="button">Save</button>
  </div>
</section>
