// demo/src/angular/profile.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-profile',
  standalone: true,
  template: `
    <section>
      <h1>Profile</h1>
      <div class="card">
        <div class="form-field">
          <label for="spa-profile-field">Display name</label>
          <input id="spa-profile-field" type="text" placeholder="Your name" />
        </div>
        <button class="btn-primary" type="button">Save</button>
      </div>
    </section>
  `,
})
export class ProfileComponent {}

// demo/src/svelte/Profile.svelte
<section>
  <h1>Profile</h1>
  <div class="card">
    <div class="form-field">
      <label for="spa-profile-field">Display name</label>
      <input id="spa-profile-field" type="text" placeholder="Your name" />
    </div>
    <button class="btn-primary" type="button">Save</button>
  </div>
</section>
