// demo/src/angular/app.component.ts
import { Component, type OnInit } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { resumeTour } from '@tours/core';
import { playerState, wireDemoPanel, makeSpaTour } from '../common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <header class="site-header">
      <a class="logo" routerLink="/">Community</a>
      <nav class="site-nav">
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Home</a>
        <a routerLink="/profile" routerLinkActive="active">Profile</a>
        <a href="spa.html">Vanilla</a>
      </nav>
    </header>
    <main><router-outlet /></main>
  `,
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    wireDemoPanel();
    // Continue if the page was reloaded mid-tour.
    resumeTour(makeSpaTour('demo-spa-angular', 'Angular'), { state: playerState });
  }
}

// demo/src/vue/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { RouterLink, RouterView } from 'vue-router';
import { resumeTour } from '@tours/core';
import { playerState, wireDemoPanel, makeSpaTour } from '../common';

onMounted(() => {
  wireDemoPanel();
  // Continue if the page was reloaded mid-tour.
  resumeTour(makeSpaTour('demo-spa-vue', 'Vue'), { state: playerState });
});
</script>

<template>
  <header class="site-header">
    <RouterLink class="logo" to="/">Community</RouterLink>
    <nav class="site-nav">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
      <a href="spa.html">Vanilla</a>
    </nav>
  </header>
  <main>
    <RouterView />
  </main>
</template>
