// demos/vue/src/components/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { RouterLink, RouterView } from 'vue-router';
import { resumeTour } from '@tours/core';
import { playerState, wireDemoPanel, makeSpaTour } from '@tours/demo-shared';

onMounted(() => {
  wireDemoPanel();
  resumeTour(makeSpaTour('demo-spa-vue', 'Vue'), { state: playerState });
});
</script>

<template>
  <header class="site-header">
    <RouterLink class="logo" to="/">Community</RouterLink>
    <nav class="site-nav">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
  </header>
  <main>
    <RouterView />
  </main>
</template>

// demos/svelte/src/App.svelte
<script lang="ts">
  import Router, { link } from 'svelte-spa-router';
  import { onMount } from 'svelte';
  import { resumeTour } from '@tours/core';
  import { playerState, wireDemoPanel, makeSpaTour } from '@tours/demo-shared';
  import Home from './components/Home.svelte';
  import Profile from './components/Profile.svelte';

  const routes = { '/': Home, '/profile': Profile };

  onMount(() => {
    wireDemoPanel();
    resumeTour(makeSpaTour('demo-spa-svelte', 'Svelte'), { state: playerState });
  });
</script>

<header class="site-header">
  <a class="logo" href="/" use:link>Community</a>
  <nav class="site-nav">
    <a href="/" use:link>Home</a>
    <a href="/profile" use:link>Profile</a>
  </nav>
</header>

<main>
  <Router {routes} />
</main>
