// demo/src/vue/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { RouterLink, RouterView } from 'vue-router';
import { resumeTour } from '@tours/core';
import { playerState, wireDemoPanel, makeSpaTour } from '../common';

onMounted(() => {
  wireDemoPanel();
  // Continue if the page was reloaded mid-tour.
  resumeTour(makeSpaTour('demo-spa-vue', 'Vue'), { state: playerState });
});
</script>

<template>
  <header class="site-header">
    <RouterLink class="logo" to="/">Community</RouterLink>
    <nav class="site-nav">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
      <a href="spa.html">Vanilla</a>
    </nav>
  </header>
  <main>
    <RouterView />
  </main>
</template>

// demo/src/App.svelte
<script lang="ts">
  import Router, { link } from 'svelte-spa-router';
  import { onMount } from 'svelte';
  import { resumeTour } from '@tours/core';
  import { playerState, wireDemoPanel, makeSpaTour } from './common';
  import Home from './svelte/Home.svelte';
  import Profile from './svelte/Profile.svelte';

  const routes = { '/': Home, '/profile': Profile };

  onMount(() => {
    wireDemoPanel();
    // Continue if the page was reloaded mid-tour.
    resumeTour(makeSpaTour('demo-spa-svelte', 'Svelte'), { state: playerState });
  });
</script>

<header class="site-header">
  <a class="logo" href="/" use:link>Community</a>
  <nav class="site-nav">
    <a href="/" use:link>Home</a>
    <a href="/profile" use:link>Profile</a>
    <a href="spa.html">Vanilla</a>
  </nav>
</header>

<main>
  <Router {routes} />
</main>
